[options]
addons_path =/Users/rukshanmaduranga/Desktop/Projects/odoo/odoo/addons, /Users/rukshanmaduranga/Desktop/Projects/odoo/odoo/odoo/addons, /Users/rukshanmaduranga/Desktop/Projects/odoo/odoo/addons, /Users/rukshanmaduranga/Desktop/Projects/odoo/odoo/workspace_project/custom
db_host = localhost
db_port = 5432
db_user = odoo
db_password = 0619
admin_passwd = $pbkdf2-sha512$600000$jJESolTKGQMAoLT2fk8JgQ$lvQw5.JV/pc4L3NEKKQ924t2aPdmdMCVx9oNfoURQUX2DTGA/b/m7R61DsG69xIyGTOT0dVEIZp/.mgWLFP4OQ

